services:
  database:
    image: postgres:latest
    container_name: pywallet_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rooted}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rooted}
      POSTGRES_DB: ${POSTGRES_DB:-rooted}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - pywallet-net

volumes:
  pgdata:
    driver: local

networks:
  pywallet-net:
    driver: bridge
